# Generated by Django 4.2.4 on 2023-08-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_choice_text_choice_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
